### ISSUE TITLE
EliteJournalReader is a little behind current Journal Version.

### ISSUE THREAD

**Issue by fmjensen** [MagicMau/EliteJournalReader#10]
Will EliteJournalReader be updated "in the near future"?

I would love to see the new events implemented and specifically ProspectedAsteroid event (§11.33) is one i would like to play with.

https://forums.frontier.co.uk/forums/elite-api-and-tools/ contains the current version of Elite:Dangerous Player Journal manual as y'all probably know.

**Comment by MagicMau** [comment]
Is it now? [ProspectedAsteroid ](https://github.com/MagicMau/EliteJournalReader/blob/master/EliteJournalReader/Events/ProspectedAsteroidEvent.cs )has been in [since January](https://github.com/MagicMau/EliteJournalReader/commit/eed0e5d17b6b8d0dd4f2929c59fc4df8e3dcb887). Or is it not working as expected?
This project should be up to date shortly after Frontier publishes new documentation. Next changes I expect on or near the September update.

**Comment by fmjensen** [comment]
Weird... i will examine that as soon as possible. Maybe i got a depricated version downloaded - i am sorry for the trouble if that turns out to be the case.

**Comment by fmjensen** [comment]
I am sorry for bothering you on this topic. My bad - i will close it now.

**Comment by MagicMau** [comment]
no worries, happy that this library is useful to you!
